### ISSUE TITLE
search by name

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/friend-requests-exploration#85]
The component at the top is called 'Search' but it only supports entering a full WebId.
Instead this component could be moved into the PersonLists component, and be fed with a list of full names, so that you can search by name.

**Comment by SharonStrats** [comment]
I want to document things I have  tried.  Using react-select library causes the following error.
<img width="198" alt="react-selectError" src="https://user-images.githubusercontent.com/9412507/70504653-4a04a580-1b7a-11ea-99e5-cfc4fd661324.PNG">

**Comment by SharonStrats** [comment]
Ended up doing this, however now I am working through setting options in React state.        `          <input
            className='input'
            list='friendOptions'
            onChange={onChange}
            value={query}
            name='search'
            id='search'
          />
          <datalist id='friendOptions'>`${options}`</datalist>`

**Comment by SharonStrats** [comment]
This was corrected in a previous commit.
